PythonStudy/answerSystem/17_source_code/examination_source_code/api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from account import login_views
from competition import game_views, set_views, rank_views
from business import biz_views

# account
urlpatterns = [
    url(r'^login_normal$', login_views.normal_login, name='normal_login'),
    url(r'^login_redirect$', login_views.login_redirect, name='index'),
    url(r'^login_vcode$', login_views.login_vcode, name='login_qrcode'),
    url(r'^signup$', login_views.signup, name='signup'),
    url(r'^sendmail$', login_views.sendmail, name='sendmail'),
    url(r'^resetpasswd$', login_views.reset_password, name='reset_password'),
]

# game
urlpatterns += [
    url(r'^questions$', game_views.get_questions, name='get_questions'),
    url(r'^answer$', game_views.submit_answer, name='submit_answer'),
    url(r'^entry$', game_views.userinfo_entry, name='userinfo_entry'),
    url(r'^games/s/(\w+)$', game_views.games, name='query_games'),
]

# set
urlpatterns += [
    url(r'^banks/s/(\d+)$', set_views.banks, name='query_banks'),
    url(r'^banks/detail/(?P<bank_id>\w+)$', set_views.bank_detail, name='bank_detail'),
    url(r'^banks/set$', set_views.set_bank, name='set_bank'),
]

# rank
urlpatterns += [
    url(r'^myrank$', rank_views.get_my_rank, name='my_rank'),
]

# bussiness
urlpatterns += [
    url(r'^regbiz$', biz_views.registry_biz, name='registry biz'),
    url(r'^checkbiz$', biz_views.check_biz, name='check_biz'),
]

PythonStudy/answerSystem/17_source_code/examination_source_code/competition/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url

from competition import cop_render, set_render

# 比赛url
urlpatterns = [
    url(r'^$', cop_render.home, name='index'),
    url(r'^game$', cop_render.game, name='game'),
    url(r'^result$', cop_render.result, name='result'),
    url(r'^rank$', cop_render.rank, name='rank'),
    url(r'^search$', cop_render.search, name='search'),
    url(r'^contact$', cop_render.contact, name='contact'),
    url(r'^donate$', cop_render.donate, name='donate'),
]

# 配置比赛url
urlpatterns += [
    url(r'^set$', set_render.index, name='set_index'),
    url(r'^set/bank$', set_render.set_bank, name='set_bank'),
    url(r'^set/bank/tdownload$', set_render.template_download, name='template_download'),
    url(r'^set/bank/upbank$', set_render.upload_bank, name='upload_bank'),
    url(r'^set/game$', set_render.set_game, name='set_game'),
]

PythonStudy/answerSystem/17_source_code/examination_source_code/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from account import login_render

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^index$', login_render.web_index, name='web_index'),
    url(r'^login$', login_render.web_login, name='web_login'),
    url(r'^logout$', login_render.web_logout, name='web_logout'),
]

urlpatterns += [
    url(r'^bs/', include('competition.urls', namespace='bs')),  # 比赛
    url(r'^api/', include('api.urls', namespace='api')),  # 接口
    url(r'^biz/', include('business.urls', namespace='biz')),  # 机构
    url(r'^ana/', include('analysis.urls', namespace='ana')),  # 分析
]

urlpatterns += [
    url(r'^auth/', include('account.urls', namespace='auth')),  # 微信授权
]

handler403 = login_render.error
handler404 = login_render.error
handler500 = login_render.error

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "[Quizz 管理系统]"

PythonStudy/answerSystem/17_source_code/examination_source_code/competition/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from shortuuidfield import ShortUUIDField
from utils.basemodels import CreateUpdateMixin, MediaMixin


class CompetitionKindInfo(CreateUpdateMixin):
    """比赛类别信息类"""

    IT_ISSUE = 0
    EDUCATION = 1
    CULTURE = 2
    GENERAL = 3
    INTERVIEW = 4
    REAR = 5
    GEO = 6
    SPORT = 7

    KIND_TYPES = (
        (IT_ISSUE, u'技术类'),
        (EDUCATION, u'教育类'),
        (CULTURE, u'文化类'),
        (GENERAL, u'常识类'),
        (GEO, u'地理类'),
        (SPORT, u'体育类'),
        (INTERVIEW, u'面试题')
    )

    kind_id = ShortUUIDField(_(u'比赛id'), max_length=32, blank=True, null=True, help_text=u'比赛类别唯一标识', db_index=True)
    account_id = models.CharField(_(u'出题账户id'), max_length=32, blank=True, null=True, help_text=u'商家账户唯一标识', db_index=True)
    app_id = models.CharField(_(u'应用id'), max_length=32, blank=True, null=True, help_text=u'应用唯一标识', db_index=True)
    bank_id = models.CharField(_(u'题库id'), max_length=32, blank=True, null=True, help_text=u'题库唯一标识', db_index=True)
    kind_type = models.IntegerField(_(u'比赛类型'), default=IT_ISSUE, choices=KIND_TYPES, help_text=u'比赛类型')
    kind_name = models.CharField(_(u'比赛名称'), max_length=32, blank=True, null=True, help_text=u'竞赛类别名称')

    sponsor_name = models.CharField(_(u'赞助商名称'), max_length=60, blank=True, null=True, help_text=u'赞助商名称')

    total_score = models.IntegerField(_(u'总分数'), default=0, help_text=u'总分数')
    question_num = models.IntegerField(_(u'题目个数'), default=0, help_text=u'出题数量')

    # 周期相关
    cop_startat = models.DateTimeField(_(u'比赛开始时间'), default=timezone.now, help_text=_(u'比赛开始时间'))
    period_time = models.IntegerField(_(u'答题时间'), default=60, help_text=u'答题时间(min)')
    cop_finishat = models.DateTimeField(_(u'比赛结束时间'), blank=True, null=True, help_text=_(u'比赛结束时间'))

    # 参与相关
    total_partin_num = models.IntegerField(_(u'total_partin_num'), default=0, help_text=u'总参与人数')

    class Meta:
        verbose_name = _(u'比赛类别信息')
        verbose_name_plural = _(u'比赛类别信息')

    def __unicode__(self):
        return str(self.pk)

    @property
    def data(self):
        return {
            'account_id': self.account_id,
            'app_id': self.app_id,
            'kind_id': self.kind_id,
            'kind_type': self.kind_type,
            'kind_name': self.kind_name,
            'total_score': self.total_score,
            'question_num': self.question_num,
            'total_partin_num': self.total_partin_num,
            'cop_startat': self.cop_startat,
            'cop_finishat': self.cop_finishat,
            'period_time': self.period_time,
            'sponsor_name': self.sponsor_name,
        }


class BankInfo(CreateUpdateMixin):
    """
    题库信息类
    """

    IT_ISSUE = 0
    EDUCATION = 1
    CULTURE = 2
    GENERAL = 3
    INTERVIEW = 4
    REAR = 5
    GEO = 6
    SPORT = 7

    BANK_TYPES = (
        (IT_ISSUE, u'技术类'),
        (EDUCATION, u'教育类'),
        (CULTURE, u'文化类'),
        (GENERAL, u'常识类'),
        (GEO, u'地理类'),
        (SPORT, u'体育类'),
        (INTERVIEW, u'面试题')
    )

    bank_id = ShortUUIDField(_(u'题库id'), max_length=32, blank=True, null=True, help_text=u'题库唯一标识', db_index=True)
    uid = models.CharField(_(u'用户id'), max_length=32, blank=True, null=True, help_text=u'用户唯一标识', db_index=True)
    account_id = models.CharField(_(u'商家id'), max_length=32, blank=True, null=True, help_text=u'商家账户唯一标识', db_index=True)
    bank_name = models.CharField(_(u'题库名称'), max_length=40, blank=True, null=True, help_text=u'题库名称')

    choice_num = models.IntegerField(_(u'选择题数'), default=0, help_text=u'选择题数')
    fillinblank_num = models.IntegerField(_(u'填空题数'), default=0, help_text=u'填空题数')
    bank_type = models.IntegerField(_(u'题库类型'), default=IT_ISSUE, choices=BANK_TYPES, help_text=u'题库类型')
    kind_num = models.IntegerField(_(u'比赛使用次数'), default=0, help_text=u'比赛使用次数')
    partin_num = models.IntegerField(_(u'总答题人数'), default=0, help_text=u'总答题人数')

    class Meta:
        verbose_name = _(u'题库')
        verbose_name_plural = _(u'题库')

    def __unicode__(self):
        return str(self.pk)

    @property
    def total_question_num(self):
        return self.choice_num + self.fillinblank_num

    @property
    def data(self):
        return {
            'bank_id': self.bank_id,
            'bank_name': self.bank_name,
            'choice_num': self.choice_num,
            'fillinblank_num': self.fillinblank_num,
            'bank_type': dict(self.BANK_TYPES)[self.bank_type],
            'kind_num': self.kind_num,
            'partin_num': self.partin_num,
            'total_question_num': self.total_question_num
        }


class ChoiceInfo(CreateUpdateMixin, MediaMixin):
    """
    选择题信息类
    """

    QUESTION_TYPE = 'choice'

    TXT = 1
    IMG = 2
    AUDIO = 3

    CONTENT_TYPE = (
        (TXT, u'文本'),
        (IMG, u'图片'),
        (AUDIO, u'音频'),
    )

    bank_id = models.CharField(_(u'题库id'), max_length=32, blank=True, null=True, help_text=u'题库唯一标识', db_index=True)
    ctype = models.IntegerField(_(u'题目类型'), choices=CONTENT_TYPE, default=TXT, help_text=u'题目类型')
    question = models.CharField(_(u'问题'), max_length=255, blank=True, null=True, help_text=u'题目')
    answer = models.CharField(_(u'答案'), max_length=255, blank=True, null=True, help_text=u'答案')
    item1 = models.CharField(_(u'选项1'), max_length=255, blank=True, null=True, help_text=u'选项一')
    item2 = models.CharField(_(u'选项2'), max_length=255, blank=True, null=True, help_text=u'选项二')
    item3 = models.CharField(_(u'选项3'), max_length=255, blank=True, null=True, help_text=u'选项三')
    item4 = models.CharField(_(u'选项4'), max_length=255, blank=True, null=True, help_text=u'选项四')
    source = models.CharField(_(u'出处'), max_length=255, blank=True, null=True, help_text=u'出处')

    class Meta:
        verbose_name = _(u'选择题')
        verbose_name_plural = _(u'选择题')

    def __unicode__(self):
        return str(self.pk)

    @property
    def items(self):
        tmp = []
        if self.item1:
            tmp.append(self.item1)
        if self.item2:
            tmp.append(self.item2)
        if self.item3:
            tmp.append(self.item3)
        if self.item4:
            tmp.append(self.item4)
        return tmp

    @property
    def data_without_answer(self):
        return {
            'pk': self.pk,
            'qtype': self.QUESTION_TYPE,
            'bank_id': self.bank_id,
            'ctype': self.ctype,
            'question': self.question,
            'items': self.items,
            'source': self.source,
            'media': self.media,
        }

    @property
    def data(self):
        return {
            'pk': self.pk,
            'qtype': self.QUESTION_TYPE,
            'bank_id': self.bank_id,
            'ctype': self.ctype,
            'question': self.question,
            'answer': self.answer,
            'items': self.items,
            'source': self.source,
            'media': self.media,
        }


class FillInBlankInfo(CreateUpdateMixin, MediaMixin):
    """
    填空题信息类
    """

    QUESTION_TYPE = 'fillinblank'

    TXT = 1
    IMG = 2
    AUDIO = 3

    CONTENT_TYPE = (
        (TXT, u'文本'),
        (IMG, u'图片'),
        (AUDIO, u'音频'),
    )

    bank_id = models.CharField(_(u'题库id'), max_length=32, blank=True, null=True, help_text=u'题库唯一标识', db_index=True)
    ctype = models.IntegerField(_(u'题目类型'), choices=CONTENT_TYPE, default=TXT, help_text=u'题目类型')
    question = models.CharField(_(u'问题'), max_length=255, blank=True, null=True, help_text=u'题目')
    answer = models.CharField(_(u'答案'), max_length=255, blank=True, null=True, help_text=u'答案')
    source = models.CharField(_(u'出处'), max_length=255, blank=True, null=True, help_text=u'出处')

    class Meta:
        verbose_name = _(u'填空题')
        verbose_name_plural = _(u'填空题')

    def __unicode__(self):
        return str(self.pk)

    @property
    def data_without_answer(self):
        return {
            'pk': self.pk,
            'bank_id': self.bank_id,
            'ctype': self.ctype,
            'question': self.question,
            'qtype': self.QUESTION_TYPE,
            'source': self.source
        }

    @property
    def data(self):
        return {
            'pk': self.pk,
            'bank_id': self.bank_id,
            'ctype': self.ctype,
            'question': self.question,
            'qtype': self.QUESTION_TYPE,
            'answer': self.answer,
            'source': self.source
        }


class CompetitionQAInfo(CreateUpdateMixin):
    """答题记录信息类"""

    UNCOMPLETED = 0
    COMPLETED = 1
    OVERTIME = 2

    STATUS_CHOICES = (
        (UNCOMPLETED, u'未完成'),
        (COMPLETED, u'已完成'),
        (OVERTIME, u'超时')
    )

    status = models.IntegerField(_(u'答题状态'), choices=STATUS_CHOICES, default=0, help_text=u'答题状态')
    kind_id = models.CharField(_(u'比赛id'), max_length=32, blank=True, null=True, help_text=u'比赛类别唯一标识', db_index=True)
    qa_id = ShortUUIDField(_(u'问题id'), max_length=32, blank=True, null=True, help_text=u'QA 唯一标识', db_index=True)
    uid = models.CharField(_(u'用户id'), max_length=32, blank=True, null=True, help_text=u'用户唯一标识', db_index=True)

    # 问题答案相关
    qsrecord = models.TextField(_('问题记录'), max_length=10000, blank=True, null=True, help_text=u'问题记录')
    asrecord = models.TextField(_('答案记录'), max_length=10000, blank=True, null=True, help_text=u'答案记录')
    aslogrecord = models.TextField(_('答案提交记录'), max_length=10000, blank=True, null=True, help_text=u'答案提交记录')

    # 耗费时间相关
    started_stamp = models.BigIntegerField(_(u'开始时间戳'), default=0, help_text=u'开始时间戳(毫秒)')
    finished_stamp = models.BigIntegerField(_(u'结束时间戳'), default=0, help_text=u'结束时间戳(毫秒)')
    expend_time = models.IntegerField(_(u'耗时'), default=0, help_text=u'耗费时间(毫秒)')

    started = models.BooleanField(_(u'已开始'), default=False, help_text=u'是否开始', db_index=True)

PythonStudy/answerSystem/17_source_code/examination_source_code/competition/views.py
# -*- coding: utf-8 -*-


def index(request):
    pass

PythonStudy/answerSystem/17_source_code/examination_source_code/web/templates/competition/index.html
{% extends '../base.html' %}
{% block title %}比赛首页{% endblock %}
{% block content %}
    <div class="list-group">
        <h2 class="text-center">{{ kind_info.kind_name }}</h2><br />
        <div class="list-group-item">出题机构：<strong style="color: red;font-size: 18px;">{{ kind_info.sponsor_name }}</strong></div>
        <div class="list-group-item">题目总分：{{ kind_info.total_score }}</div>
        <div class="list-group-item">题目数量：{{ kind_info.question_num }}</div>
        <div class="list-group-item">题库大小：{{ bank_info.total_question_num }}道题</div>
        <div class="list-group-item">开始时间：{{ kind_info.cop_startat }}</div>
        <div class="list-group-item">结束时间：{{ kind_info.cop_finishat }}</div>
        <br />
        <div>
            <a href="/bs/rank?uid={{ user_info.uid }}&kind_id={{ kind_info.kind_id }}" class="btn btn-success" style="float: right">查看排行榜</a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a id="startAnswer" href="#" class="btn btn-primary" style="float: left">开始挑战</a>
            <!--span class="badge" style="float: right;">快来参与吧~</span-->
        </div>
    </div>
    <div id="formModal" class="modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <button class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-title">
                    <h2 class="text-center">请先填写一些答题必要的信息</h2>
                </div>
                <div id="frmBody" class="modal-body">
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
      $.ajaxSetup({
          data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
      });
      var isShowUserinfo = {{ is_show_userinfo|safe }};
      var userinfoHasEntered = {{ userinfo_has_enterd|safe }};
      var fields = {{ userinfo_fields|safe }};
      var optionFields = {{ option_fields|safe }};
      var fieldRegexes = {{ field_regexes|safe }};
      var optionFieldNameList = [];
      for(var i in optionFields.split('#')){optionFieldNameList[i]=optionFields.split('#')[i].split(':')[0]}

      $('#startAnswer').click(function () {
          if(isShowUserinfo && !userinfoHasEntered){
              var strHTML = "<form id=\"formBody\" class=\"form-group\">";
              for(var i in fields){
                  if(!checkInList(i, optionFieldNameList)){
                      strHTML += "<div class=\"form-group\">";
                      strHTML += "<label for=\"frmId" + i + "\">" + fields[i] + "</label>";
                      strHTML += "<input id=\"frmId" + i + "\" class=\"form-control\" type=\"text\" placeholder=\"\">";
                      strHTML += "</div>";
                  }else if(checkInList(i, optionFieldNameList)){
                      opl = optionFields.split('#');
                      for(var j in opl) {
                          if(opl[j].startsWith(i)) {
                              strHTML += "<label for=\"frmId" + i + "\">" + fields[i] + "</label>";
                              strHTML += "<select id=\"frmId" + i + "\" class=\"form-control\">\n";
                              var t = opl[j].split(':')[1].split(',');
                              for(var k in t) {
                                  strHTML += "<option>" + t[k] + "</option>\n";
                              }
                              strHTML += "</select>";
                          }
                      }
                  }else{
                  }
              }

              strHTML += "<br />";
              strHTML += "<div class=\"text-right\">\n" +
                  "<button id=\"frmSubmit\" class=\"btn btn-primary\" type=\"submit\">提交</button>\n" +
                  "<button id=\"frmCancel\" class=\"btn btn-danger\" data-dismiss=\"modal\">取消</button>\n" +
                  "</div>";
              strHTML += "</form>";

              document.getElementById('frmBody').innerHTML = strHTML;
              $('#formModal').modal('show');
              $('#frmSubmit').click(function () {
                  var result = '';
                  for(var i in fields){
                      if(!$('#frmId' + i).val().match(getRegex(fieldRegexes, i))) {
                          $('#frmId' + i).attr('placeholder', getRegexDesc(fieldRegexes, i));
                          $('#frmId' + i).css('border', '1px solid red');
                          return false;
                      }
                      else {
                          $('#frmId' + i).css('border', '1px solid #C1FFC1');
                          result += i + ',' + $('#frmId' + i).val() + '#';
                      }
                  }
                  if(result) {
                      $.ajax({
                          url: "/api/entry",
                          data: {
                              'kind_id': '{{ kind_info.kind_id|safe }}',
                              'uid': '{{ user_info.uid|safe }}',
                              'result': result,
                          },
                          type: 'post',
                          dataType: 'json',
                          success: function (res) {
                              if (res.status === 200) {
                                  window.location.href = '/bs/game?uid=' + res.data.user_info.uid + '&kind_id=' + res.data.kind_info.kind_id;
                              } else {
                                  alert('提交失败');
                              }
                          }
                      });
                      return false;
                  }
              })
          }else
          {
              window.location.href = '{% url 'bs:game' %}?uid={{ user_info.uid }}&kind_id={{ kind_info.kind_id }}';
          }
      });

    function checkInList(s, l) {
        for(var i in l){
            if(s === l[i]){
                return true;
            }
        }
        return false;
    }

    function getRegex(l, field) {
        for(var i in l){
            if(l[i].field_name === field) {
                return l[i].regex;
            }
        }
    }

    function getRegexDesc(l, field) {
        for(var i in l){
            if(l[i].field_name === field) {
                return l[i].description;
            }
        }
    }
    </script>
{% endblock %}

PythonStudy/answerSystem/17_source_code/examination_source_code/web/templates/competition/rank.html
{% extends 'base.html' %}
{% block title %}排行榜{% endblock %}
{% block content %}
    <h2>排行榜</h2><br />
    <a class="btn btn-primary" href="/index{% if request.session.uid %}?uid={{ request.session.uid }}{% else %}{% endif %}">回首页</a>
    <a class="btn btn-primary" href="/bs{% if request.session.uid %}?uid={{ request.session.uid }}{% else %}{% endif %}&kind_id={{ kind_info.kind_id }}" style="margin-left: 20px;">去答题</a>
    <ul id="myRank" style="float: right"></ul>
    <table style="margin-top: 15px;" class="table table-hover">
        <tr>
            <th>排名</th>
            <th>昵称</th>
            <th>得分</th>
            <th>用时</th>
        </tr>
        {% for r in rank %}
        <tr>
            <td>{% if r.rank %}<b style="color:red">{{ r.rank }}</b>{% else %}暂无{% endif %}</td>
            <td>{% if r.nickname %}{{ r.nickname }}{% else %}暂无{% endif %}</td>
            <td>{% if r.score %}{{ r.score }}{% else %}0{% endif %}</td>
            <td>{% if r.time %}{{ r.time }}{% else %}暂无{% endif %}s</td>
        </tr>
        {% endfor %}
    </table>
    <script>
        $(document).ready(function () {
            $.ajax({
                url: '/api/myrank',
                data: {
                    uid: '{{ request.session.uid|safe }}',
                    kind_id: '{{ kind_info.kind_id|safe }}'
                },
                dataType: 'json',
                type: 'get',
                success: function (res) {
                    if(res.status === 200) {
                        var strHTML = '';
                        if(res.data.rank) {
                            strHTML += "<li><b>我的排名: 第 <p style=\"color: red;display:inline\">" + res.data.rank + "</p> 名</b></li>";
                            strHTML += "<li><b>我的用时: <p style=\"color: red\;display:inline\">" + res.data.time / 1000 + "</p>秒</b></li>";
                        }
                        else{
                            strHTML += "<li><b>我的排名: 暂无</b></li>";
                            strHTML += "<li><b>我的用时: 暂无</b></li>";
                        }
                        $('#myRank').html(strHTML);
                    }
                }
            })
        })
    </script>
{% endblock %}

PythonStudy/answerSystem/17_source_code/examination_source_code/web/templates/competition/result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}答题结果{% endblock %}
{% block content %}
    <h2 class="text-center">成绩单</h2><br />
    <ul class="list-group">
    {% if rank <= 3 %}
        <li class="list-group-item list-group-item-success">得分: <b>{{ qa_info.score }}</b> 分</li>
        <li class="list-group-item list-group-item-success">耗时: <b>{{ qa_info.time }}</b> s</li>
        <li class="list-group-item list-group-item-success">答对题数: <b>{{ qa_info.correct_num }}</b></li>
        <li class="list-group-item list-group-item-success">答错题数: <b>{{ qa_info.incorrect_num }}</b></li>
        <li class="list-group-item list-group-item-success">
            当前排名: 第 <b style="color: red;font-size: 20px;">{{ rank }}</b> 名
            <h4 style="color:gray;font-size: 20px">成绩不错，继续努力哦~</h4>
        </li>
        <li id="goBack" class="btn btn-primary" style="margin-top: 40px;">回首页</li>
        <li id="tryAgain" class="btn btn-primary" style="margin-top: 40px; margin-left: 30px">再试试</li>
        <!--li id="goHome" class="btn btn-primary" style="margin-top: 40px; margin-left: 30px;">其他比赛</li-->
        <li id="goRank" class="btn btn-success" style="margin-top: 40px; float: right">查看排行榜</li>
    {% else %}
        <li class="list-group-item list-group-item-danger">得分: <b>{{ qa_info.score }}</b> 分</li>
        <li class="list-group-item list-group-item-danger">耗时: <b>{{ qa_info.time }}</b> s</li>
        <li class="list-group-item list-group-item-danger">答对题数: <b>{{ qa_info.correct_num }}</b></li>
        <li class="list-group-item list-group-item-danger">答错题数: <b>{{ qa_info.incorrect_num }}</b></li>
        <li id="currentRank" class="list-group-item list-group-item-danger">
            当前排名: 第 <b style="color: red;font-size: 20px;">{{ rank }}</b> 名
            <h4 style="color:gray;font-size: 20px">成绩不理想，再试试吧~</h4>
        </li>
        <li id="goBack" class="btn btn-primary" style="margin-top: 36px;">回首页</li>
        <li id="tryAgain" class="btn btn-primary" style="margin-top: 36px; margin-left: 30px;">再试试</li>
        <!--li id="goHome" class="btn btn-primary" style="margin-top: 40px; margin-left: 30px;">其他比赛</li-->
        <li id="goRank" class="btn btn-success" style="margin-top: 36px; float: right">查看排行榜</li>
    {% endif %}
    </ul>
    <script type="text/javascript">
      $('#goRank').click(function () {
          window.location.href = '/bs/rank?uid={{ request.session.uid }}&kind_id={{ kind_info.kind_id }}';
      });
      $('#tryAgain').click(function () {
          window.location.href = '/bs?uid={{ request.session.uid }}&kind_id={{ kind_info.kind_id }}';
      });
      $('#goHome').click(function () {
          window.location.href = '/index{% if request.session.uid %}?uid={{ request.session.uid }}{% else %}{% endif %}';
      });
      $('#goBack').click(function () {
          window.location.href = '/index{% if request.session.uid %}?uid={{ request.session.uid }}{% else %}{% endif %}';
      })
    </script>
{% endblock %}

PythonStudy/answerSystem/17_source_code/examination_source_code/web/templates/competition/search.html
{% extends 'base.html' %}
{% block title %}查询结果{% endblock %}
{% block content %}
    <div class="list-group ">
      <h2 class="text-center">查询结果</h2><br />
      {% for r in result %}
          <a href="{% url 'bs:index' %}?uid={{ request.session.uid }}&kind_id={{ r.kind_id }}" class="list-group-item">{{ r.kind_name }}<p style="float: right">举办机构: {% if r.sponsor_name == None %} 无 {% else %} {{ r.sponsor_name }} {% endif %}</p></a>
      {% endfor %}
    </div>
{% endblock %}